package utils

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/bblfsh/sdk/v3/driver/manifest/discovery"

	"bitbucket.org/creachadair/shell"
	"github.com/google/go-github/v27/github"
	"golang.org/x/oauth2"
	"gopkg.in/src-d/go-errors.v1"
	"gopkg.in/src-d/go-log.v1"
)

const (
	commitMsg = "autogenerated changes"
	org       = "bblfsh"
	tmpFolder = "/var/lib/tmp"

	// TODO(lwsanty): need to set up smth here :)
	gitUser = "grzegorz"
	gitMail = "grzegorz@brzęczyszczykiewicz"
)

var (
	errFailedToPrepareBranch = errors.NewKind("failed to prepare branch for driver %v: %v")
	errFailedToPreparePR     = errors.NewKind("failed to prepare pull request for driver %v branch %v: %v")
	errCmdFailed             = errors.NewKind("command failed: %v, output: %v")
)

type pipeLine struct {
	nodes      []pipeLineNode
	driver     discovery.Driver
	dockerfile bool
	tmpDir     string
}

type pipeLineNode struct {
	logFormat string
	logArgs   []interface{}
	command   string
}

type UpdateOptions struct {
	Branch     string
	SDKVersion string
	Script     string
	Dockerfile bool
}

func newPipeline(d discovery.Driver, o *UpdateOptions) *pipeLine {
	url := d.RepositoryURL()
	origin := getOrigin(url, o.Dockerfile)
	tmpDir := filepath.Join(tmpFolder, d.Language)

	var nodes []pipeLineNode
	nodes = append(nodes,
		pipeLineNode{
			logFormat: "creating dir %v",
			logArgs:   []interface{}{tmpDir},
			command:   fmt.Sprintf("mkdir -p %v", shell.Quote(tmpDir)),
		},
		pipeLineNode{
			logFormat: "performing git clone repository %v -> %v",
			logArgs:   []interface{}{url, tmpDir},
			command: fmt.Sprintf("git clone %[1]s %[2]s ; cd %[2]s ; "+
				"git remote rm origin ; git remote add origin %[3]s", shell.Quote(url), shell.Quote(tmpDir), origin),
		}, pipeLineNode{
			logFormat: "creating branch %v",
			logArgs:   []interface{}{o.Branch},
			command:   fmt.Sprintf("cd %s ; git checkout -b %s", shell.Quote(tmpDir), shell.Quote(o.Branch)),
		})
	if o.Script != "" {
		script := o.Script
		if o.Dockerfile {
			script = strings.Replace(script, "\n", ";", -1)
		}
		nodes = append(nodes, pipeLineNode{
			logFormat: "executing the script",
			logArgs:   []interface{}{},
			command:   fmt.Sprintf("cd %s ; %v", shell.Quote(tmpDir), script),
		})
	}
	if o.SDKVersion != "" {
		nodes = append(nodes, pipeLineNode{
			logFormat: "updating sdk to %v",
			logArgs:   []interface{}{o.SDKVersion},
			command:   fmt.Sprintf("cd %s ; go mod download ; go mod edit -require github.com/bblfsh/sdk/v3@v%v ; go run ./update.go", shell.Quote(tmpDir), o.SDKVersion),
		})
	}
	nodes = append(nodes, pipeLineNode{
		logFormat: "set git user info",
		logArgs:   []interface{}{},
		command:   fmt.Sprintf("cd %s ; git config --global user.name %v ; git config --global user.email %v", shell.Quote(tmpDir), gitUser, gitMail),
	}, pipeLineNode{
		logFormat: "committing the changes",
		logArgs:   []interface{}{},
		command:   fmt.Sprintf("cd %s ; git add -A ; git commit --signoff -m \"%s\"", shell.Quote(tmpDir), commitMsg),
	}, pipeLineNode{
		logFormat: "pushing changes",
		logArgs:   []interface{}{},
		command:   fmt.Sprintf("cd %s ; git push origin %s", shell.Quote(tmpDir), shell.Quote(o.Branch)),
	})

	return &pipeLine{nodes: nodes, driver: d, dockerfile: o.Dockerfile, tmpDir: tmpDir}
}

func (p *pipeLine) createDockerfile() (string, error) {
	const header = `FROM golang:1.12.7

ARG TOKEN

`
	content := header
	for _, c := range p.nodes {
		comment := fmt.Sprintf(c.logFormat, c.logArgs...)
		content += fmt.Sprintf("# %v\nRUN %v\n\n", comment, c.command)
	}

	_, err := os.Stat(p.tmpDir)
	if os.IsNotExist(err) {
		if err := os.MkdirAll(p.tmpDir, os.ModePerm); err != nil {
			return "", err
		}
	}

	path := filepath.Join(p.tmpDir, "Dockerfile")
	log.Infof("trying to create: %v", path)
	f, err := os.Create(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	log.Infof("preparing dockerfile:\n%v", content)
	if _, err := f.WriteString(content); err != nil {
		return "", err
	}

	return path, nil
}

func (p *pipeLine) exec() error {
	if p.dockerfile {
		dockerPath, err := p.createDockerfile()
		if err != nil {
			return err
		}
		command := fmt.Sprintf("docker build --build-arg TOKEN=%v -t %v-driver-update %v",
			os.Getenv("TOKEN"), p.driver.Language, filepath.Dir(dockerPath))
		return ExecCmd(command)
	}

	for _, c := range p.nodes {
		log.Infof(c.logFormat, c.logArgs...)
		if err := ExecCmd(c.command); err != nil {
			return errFailedToPrepareBranch.New(p.driver.Language, err)
		}
	}
	return nil
}

func (p *pipeLine) close() {
	os.RemoveAll(p.tmpDir)
}

// PrepareBranch does the next steps:
// 1) clones driver's master branch
// 2) creates new branch
// 3) executes custom script if it's not empty
// 4) updates SDK version if it's not empty
// 5) commits and pushes changes to the previously created branch
func PrepareBranch(d discovery.Driver, o *UpdateOptions) error {
	p := newPipeline(d, o)
	defer p.close()
	if err := p.exec(); err != nil {
		return err
	}

	log.Infof("driver %v: branch %v has been successfully created", d.Language, o.Branch)
	return nil
}

// PreparePR creates pull request for a given driver's branch
func PreparePR(d discovery.Driver, branch string) error {
	ctx := context.Background()
	client := github.NewClient(oauth2.NewClient(ctx, oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: os.Getenv("TOKEN")},
	)))

	pr, _, err := client.PullRequests.Create(ctx, org, d.Language+"-driver", &github.NewPullRequest{
		Title:               &branch,
		Head:                &branch,
		Base:                strPtr("master"),
		Body:                strPtr(commitMsg),
		MaintainerCanModify: newTrue(),
	})
	if err != nil {
		return errFailedToPreparePR.New(d.Language, branch, err)
	}

	log.Infof("driver %v: pull request %v has been successfully created", d.Language, *pr.ID)
	return nil
}

// ExecCmd executes the specified Bash script. If execution fails, the error contains
// the combined output from stdout and stderr of the script.
// Do not use this for scripts that produce a large volume of output.
func ExecCmd(command string) error {
	cmd := exec.Command("bash", "-c", command)

	data, err := cmd.CombinedOutput()
	log.Debugf("command output: %v", string(data))
	if err != nil {
		return errCmdFailed.New(err, string(data))
	}

	return nil
}

func getOrigin(url string, isDockerfile bool) string {
	token := "${TOKEN}"
	if !isDockerfile {
		token = os.Getenv("TOKEN")
	}
	return strings.Replace(url, "github.com", gitUser+":"+token+"@github.com", -1) + ".git"
}

func strPtr(s string) *string {
	return &s
}

func newTrue() *bool {
	b := true
	return &b
}
