language: go

go:
  - '1.11.x'
  - '1.12.x'
  - tip

services:
  - docker

go_import_path: github.com/bblfsh/sdk

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

before_install:
  - cd $GOPATH/src/github.com/bblfsh/sdk
  - make validate-commit
  - go mod download

script:
  - make test-coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
