language: go

go:
  - '1.10'
  - '1.11'
  - tip

go_import_path: gopkg.in/bblfsh/sdk.v2

matrix:
  fast_finish: true
  allow_failures:
    - go: tip


before_install:
  - cd $GOPATH/src/gopkg.in/bblfsh/sdk.v2
  - make validate-commit
  - wget -O dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && chmod +x dep
  - ./dep ensure --vendor-only

script:
  - make test-coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
