# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  version = "v2.14.x"
  name = "gopkg.in/bblfsh/sdk.v2"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
    name = "gopkg.in/bblfsh/sdk.v2"
    unused-packages = false

