// generated by jsonenums -type=Status; DO NOT EDIT

package protocol

import (
	"encoding/json"
	"fmt"
)

var (
	_StatusNameToValue = map[string]Status{
		"Ok":    Ok,
		"Error": Error,
		"Fatal": Fatal,
	}

	_StatusValueToName = map[Status]string{
		Ok:    "Ok",
		Error: "Error",
		Fatal: "Fatal",
	}
)

func init() {
	var v Status
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_StatusNameToValue = map[string]Status{
			interface{}(Ok).(fmt.Stringer).String():    Ok,
			interface{}(Error).(fmt.Stringer).String(): Error,
			interface{}(Fatal).(fmt.Stringer).String(): Fatal,
		}
	}
}

// MarshalJSON is generated so Status satisfies json.Marshaler.
func (r Status) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _StatusValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Status: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Status satisfies json.Unmarshaler.
func (r *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}
	v, ok := _StatusNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Status %q", s)
	}
	*r = v
	return nil
}
