// Code generated by "stringer -type=Role"; DO NOT EDIT.

package uast

import "fmt"

const _Role_name = "SimpleIdentifierQualifiedIdentifierExpressionStatementOpEqualOpNotEqualOpLessThanOpLessThanEqualOpGreaterThanOpGreaterThanEqualOpSameOpNotSameOpContainsOpNotContainsFileOpBooleanAndOpBooleanOrOpBooleanNotOpBooleanXorPackageDeclarationImportDeclarationImportPathImportAliasFunctionDeclarationTypeDeclarationVisibleFromInstanceVisibleFromTypeVisibleFromSubtypeVisibleFromPackageVisibleFromSubpackageVisibleFromModuleVisibleFromFriendVisibleFromWorldIfIfConditionIfBodyIfElseSwitchSwitchCaseSwitchCaseConditionSwitchCaseBodySwitchDefaultForForInitForExpressionForUpdateForBodyForEachWhileWhileConditionWhileBodyDoWhileDoWhileConditionDoWhileBodyBreakContinueBlockBlockScopeReturnTryTryBodyTryCatchTryFinallyThrowAssertCallCallReceiverCallCalleeCallPositionalArgumentCallNamedArgumentCallNamedArgumentNameCallNamedArgumentValueNoopLiteralNullLiteralStringLiteralNumberLiteralTypeLiteralTypePrimitiveTypeAssignmentAssignmentVariableAssignmentValueThisCommentDocumentationWhitespace"

var _Role_index = [...]uint16{0, 16, 35, 45, 54, 61, 71, 81, 96, 109, 127, 133, 142, 152, 165, 169, 181, 192, 204, 216, 234, 251, 261, 272, 291, 306, 325, 340, 358, 376, 397, 414, 431, 447, 449, 460, 466, 472, 478, 488, 507, 521, 534, 537, 544, 557, 566, 573, 580, 585, 599, 608, 615, 631, 642, 647, 655, 660, 670, 676, 679, 686, 694, 704, 709, 715, 719, 731, 741, 763, 780, 801, 823, 827, 834, 845, 858, 871, 882, 886, 899, 909, 927, 942, 946, 953, 966, 976}

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return fmt.Sprintf("Role(%d)", i+1)
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
