// Code generated by "stringer -type=Role"; DO NOT EDIT

package uast

import "fmt"

const _Role_name = "SimpleIdentifierQualifiedIdentifierOpBitwiseLeftShiftOpBitwiseRightShiftOpBitwiseUnsignedRightShiftOpBitwiseOrOpBitwiseXorOpBitwiseAndExpressionStatementOpEqualOpNotEqualOpLessThanOpLessThanEqualOpGreaterThanOpGreaterThanEqualOpSameOpNotSameOpContainsOpNotContainsOpPreIncrementOpPostIncrementOpPreDecrementOpPostDecrementOpNegativeOpPositiveOpBitwiseComplementOpDereferenceOpTakeAddressFileOpBooleanAndOpBooleanOrOpBooleanNotOpBooleanXorOpAddOpSubstractOpMultiplyOpDivideOpModPackageDeclarationImportDeclarationImportPathImportAliasFunctionDeclarationFunctionDeclarationBodyFunctionDeclarationNameFunctionDeclarationReceiverFunctionDeclarationArgumentFunctionDeclarationArgumentNameFunctionDeclarationArgumentDefaultValueFunctionDeclarationVarArgsListTypeDeclarationVisibleFromInstanceVisibleFromTypeVisibleFromSubtypeVisibleFromPackageVisibleFromSubpackageVisibleFromModuleVisibleFromFriendVisibleFromWorldIfIfConditionIfBodyIfElseSwitchSwitchCaseSwitchCaseConditionSwitchCaseBodySwitchDefaultForForInitForExpressionForUpdateForBodyForEachWhileWhileConditionWhileBodyDoWhileDoWhileConditionDoWhileBodyBreakContinueBlockBlockScopeReturnTryTryBodyTryCatchTryFinallyThrowAssertCallCallReceiverCallCalleeCallPositionalArgumentCallNamedArgumentCallNamedArgumentNameCallNamedArgumentValueNoopBooleanLiteralByteLiteralByteStringLiteralCharacterLiteralListLiteralMapLiteralNullLiteralNumberLiteralRegexpLiteralSetLiteralStringLiteralTupleLiteralTypeLiteralOtherLiteralTypePrimitiveTypeAssignmentAssignmentVariableAssignmentValueAugmentedAssignmentAugmentedAssignmentOperatorAugmentedAssignmentVariableAugmentedAssignmentValueThisCommentDocumentationWhitespace"

var _Role_index = [...]uint16{0, 16, 35, 53, 72, 99, 110, 122, 134, 144, 153, 160, 170, 180, 195, 208, 226, 232, 241, 251, 264, 278, 293, 307, 322, 332, 342, 361, 374, 387, 391, 403, 414, 426, 438, 443, 454, 464, 472, 477, 495, 512, 522, 533, 552, 575, 598, 625, 652, 683, 722, 752, 767, 786, 801, 819, 837, 858, 875, 892, 908, 910, 921, 927, 933, 939, 949, 968, 982, 995, 998, 1005, 1018, 1027, 1034, 1041, 1046, 1060, 1069, 1076, 1092, 1103, 1108, 1116, 1121, 1131, 1137, 1140, 1147, 1155, 1165, 1170, 1176, 1180, 1192, 1202, 1224, 1241, 1262, 1284, 1288, 1302, 1313, 1330, 1346, 1357, 1367, 1378, 1391, 1404, 1414, 1427, 1439, 1450, 1462, 1466, 1479, 1489, 1507, 1522, 1541, 1568, 1595, 1619, 1623, 1630, 1643, 1653}

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return fmt.Sprintf("Role(%d)", i+1)
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
