// Code generated by "stringer -type=Role"; DO NOT EDIT.

package uast

import "fmt"

const _Role_name = "SimpleIdentifierQualifiedIdentifierOpBitwiseLeftShiftOpBitwiseRightShiftOpBitwiseOrOpBitwiseXorOpBitwiseAndExpressionStatementOpEqualOpNotEqualOpLessThanOpLessThanEqualOpGreaterThanOpGreaterThanEqualOpSameOpNotSameOpContainsOpNotContainsFileOpBooleanAndOpBooleanOrOpBooleanNotOpBooleanXorPackageDeclarationImportDeclarationImportPathImportAliasFunctionDeclarationTypeDeclarationVisibleFromInstanceVisibleFromTypeVisibleFromSubtypeVisibleFromPackageVisibleFromSubpackageVisibleFromModuleVisibleFromFriendVisibleFromWorldIfIfConditionIfBodyIfElseSwitchSwitchCaseSwitchCaseConditionSwitchCaseBodySwitchDefaultForForInitForExpressionForUpdateForBodyForEachWhileWhileConditionWhileBodyDoWhileDoWhileConditionDoWhileBodyBreakContinueBlockBlockScopeReturnTryTryBodyTryCatchTryFinallyThrowAssertCallCallReceiverCallCalleeCallPositionalArgumentCallNamedArgumentCallNamedArgumentNameCallNamedArgumentValueNoopLiteralNullLiteralStringLiteralNumberLiteralTypeLiteralTypePrimitiveTypeAssignmentAssignmentVariableAssignmentValueThisCommentDocumentationWhitespace"

var _Role_index = [...]uint16{0, 16, 35, 53, 72, 83, 95, 107, 117, 126, 133, 143, 153, 168, 181, 199, 205, 214, 224, 237, 241, 253, 264, 276, 288, 306, 323, 333, 344, 363, 378, 397, 412, 430, 448, 469, 486, 503, 519, 521, 532, 538, 544, 550, 560, 579, 593, 606, 609, 616, 629, 638, 645, 652, 657, 671, 680, 687, 703, 714, 719, 727, 732, 742, 748, 751, 758, 766, 776, 781, 787, 791, 803, 813, 835, 852, 873, 895, 899, 906, 917, 930, 943, 954, 958, 971, 981, 999, 1014, 1018, 1025, 1038, 1048}

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return fmt.Sprintf("Role(%d)", i+1)
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
